version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRESL_PASSWORD: password
